### ISSUE TITLE
New countries coverage -  Bosnia, Namibia, Liechtenstein, and Paraguay

### ISSUE THREAD

**Issue by dzak83** [slashP/Vali#1]
Hi,
Thanks for preparing and sharing this tool. Any chance you can add recently released countries: Bosnia, Namibia, Liechtenstein, and Paraguay ?

Thanks!

**Comment by slashP** [comment]
I will probably add Liechtenstein within a week. The other countries you list are not yet published, only confirmed, so we are all waiting for those.

**Comment by dzak83** [comment]
Thanks!

**Comment by slashP** [comment]
Added now. From v. 0.6.4.
