### ISSUE TITLE
Issues running on Mac

### ISSUE THREAD

**Issue by adamkoch** [slashP/Vali#4]
Thanks for the tool. Is it possible to run Vali on mac? The install of .net and CLI all seemed to work fine for me.

But the main issue seems to be that it keeps trying to write the data downloads and config files to /usr/share/Vali - that is a protected directory on mac (even hard to access with root).

So i tried setting the download directory:
`vali set-download-folder [local folder]`

But setting the folder requires writing to the config file which it also stores in /usr/share/Vali which fails.

Question: is there a way to set the configuration file location via environment variable or some other way?

Thanks!

**Comment by slashP** [comment]
There has not been a way to run it on Mac. But I like your suggestion to use environment variable, so I implemented that now and pushed it as version 0.7.2. Would you have a chance to test it (I don't have a mac)?

Set environment variable `VALI_DOWNLOAD_FOLDER` to the directory of choice. Downloaded files will be inside `Vali/[CountryCode]` in the specified directory. Example with env variable set to `C:\dev\priv\vali-data-test` below:

![image](https://github.com/user-attachments/assets/c6226f6c-385b-48c9-8c6d-8687ed84f7c9)

**Comment by adamkoch** [comment]
Thank you! That worked perfectly. All runs on Mac fine now, at least the few samples I tested worked.

So is download folder the only thing stored in the config file? The other solution would be to use an env variable to choose/set the location of the config file. That would allow setting download folder via the config file as well but also any other config settings (but not sure there are any!).

**Comment by slashP** [comment]
Ok, great! And thanks. For now there is nothing else in the config file, so I think it's fine.
